---
version: "3.9"
services:
  app:
    image: scra:1.0
    build:
      context: .
    ports:
      - target: 8080
        published: 8080
        protocol: "tcp"
        mode: "host"
    environment:
      - MYSQL_SERVER=mysql_db
    networks:
      - app-net
      - db-net
    depends_on: 
      - mysql_db
  mysql_db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=less-db
      - MYSQL_USER=less
      - MYSQL_PASSWORD=less
    networks:
      - db-net
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/mysql


volumes:
  dbdata:
  
networks:
  app-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.101.0/24
  db-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.102.0/24