---
version: "3.9"
services:
  app:
    image: scra:1.0
    build:
      context: .
    networks:
      - students-net
      - students-private-net
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    environment:
      - MYSQL_SERVER=mysql-db
    depends_on: 
      - mysql-db
  mysql-db:
    image: mysql:5.6
    networks:
      - students-private-net
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=lessdb
      - MYSQL_USER=less
      - MYSQL_PASSWORD=less
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/mysql

volumes:
  dbdata:

networks:
  students-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.101.0/24
  students-private-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.102.0/24